version: '2' # specify docker-compose version

# Define the services/containers to be run
services:

  rr-content-layer: # name of the first service
    image: rr-content-layer
    build:
      context: rr-content-layer
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /data/rr-content-layer
  rr-web-server: #name of the second service
    build: rr-web-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
  rr-web-client: # name of the third service
    build: rr-web-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding

  
  